#!/usr/bin/env python3
from init import *
import argparse


def get_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Free the disk space.')
    parsed_args = parser.parse_args()
    return parsed_args


if __name__ == '__main__':
    args = get_args()

    execute('sudo apt clean')
    execute('rm -rf ~/.local/share/Trash/*')
    execute('rm -rf ~/.cache/vmware')
    output = capture("/bin/bash -c '\n"
                     'readarray -t recycle_dirs < <(sudo find / -type d -name ".Trash-*" 2>/dev/null) &&\n'
                     'for dir in "${recycle_dirs[@]}"; do \n'
                     'echo "$dir" \n'
                     "done'").stdout
    for trash_dir in output.strip().split('\n'):
        execute(f'sudo rm -rf {trash_dir}')
