services:
  {SERVICE}:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - {MYBRIDGE}
    ports:
      - 22
    restart: unless-stopped
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:{PROJECT_DIR}
networks:
  {MYBRIDGE}:
    external: true
