# show the debug info
debug: true
# the file stores the variables needed in running
vars_file: vars.json
# the remote root url of the files can be retrieved in running
remote_url: http://fs
# the interval after a command is finished
interval: 0.5
# the dir of the files needed in running, set empty to use the default value
packages_dir: '/media/a/3e2d066a-20d6-47a0-bea7-7d57d96c6d15/Files'
