FROM remote_pycharm:latest
COPY --chown=$USER_NAME:$USER_NAME requirements.txt .
RUN sudo pip install --no-cache-dir -r requirements.txt
RUN git config --global user.email "you@example.com" &&\
    git config --global user.name "Your Name"
