#!/usr/bin/env python3
import os
from pathlib import Path

from dotenv import load_dotenv
import rtoml


os.chdir("..")
load_dotenv()
data = rtoml.load(Path(__file__).parent.parent / "pyproject.toml")

project_name = data['project']['name']
os.system(f'./lib/container_up')
os.system(f'docker compose exec {project_name} pycharm')
