name: Pre-commit Check

on: [push, pull_request, workflow_dispatch]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        id: precommit
        run: |
          pre-commit install
          pre-commit run --all-files || echo "::warning::Pre-commit hook(s) failed."

      - name: Commit
        uses: ./.github/actions/commit
        with:
            message: 'chore: auto-fix pre-commit issues [skip ci]'
            token: ${{ secrets.GITHUB_TOKEN }}
