name: Build and Publish Python package

on:
  workflow_run:
     workflows: ["Semantic Release"]
     types:
       - completed
     branches:
       - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Check published
      id: check
      run: |
        PKG_INFO_PATH=$(find . -name PKG-INFO -type f | head -n 1)
        echo "PKG-INFO: $PKG_INFO_PATH"
        if [[ -f "$PKG_INFO_PATH" ]]; then
          NAME=$(grep '^Name:' "$PKG_INFO_PATH" | awk '{print $2}')
          VERSION=$(grep '^Version:' "$PKG_INFO_PATH" | awk '{print $2}')
          echo "name=$NAME, version=$VERSION"
        else
            echo "Error: PKG-INFO not found!" >&2
            exit 1
        fi
        RESPONSE=$(curl -s "https://pypi.org/pypi/$NAME/$VERSION/json")
        if [[ "$RESPONSE" != '{"message": "Not Found"}' ]]; then
            echo "::warning::$NAME $VERSION already exists on PyPI"
            echo "skip_upload=true" >> $GITHUB_OUTPUT
        else
            echo "skip_upload=false" >> $GITHUB_OUTPUT
        fi

    - name: Publish to PyPI
      if: steps.check.outputs.skip_upload != 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_P }}
