name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  tox:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm,
             windows-latest, windows-11-arm,
             macos-13, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        exclude:
          - os: windows-11-arm
            python-version: "3.10"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python test environment
      uses: ./.github/actions/setup-test-env
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run test
      shell: bash
      run: |
        TOX_ENV=py${{ matrix.python-version }}
        TOX_ENV=${TOX_ENV//./}
        tox --runner virtualenv -e $TOX_ENV
        coverage xml

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.os }}-py${{ matrix.python-version }}

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.os }}-py${{ matrix.python-version }}
